<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Member_model');
       $this->load->model('Admin_model');
      
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('home');
			
			
		}
		
		if(!$this->input->post())
		{
			$this->load->view('Login2');
		}
		else
		{
			$username_member=$this->input->post('username');
			$password_member=$this->input->post('password');
			
			$cek_login=$this->Member_model->cek_login($username_member,$password_member);
			$cek_login_admin=$this->Admin_model->cek_login($username_member,$password_member);
			

			if(!empty($cek_login))
				
			{
				$this->session->set_userdata('logined', true);
				$this->session->set_userdata('username_member',$username_member);
				$this->session->set_userdata('status','member');
				$data=array();

			//	$this->session->set_userdata('cart',$data);		????
				redirect("home");								
				//print_r("berhasil login member");				????
			}
			else if (!empty($cek_login_admin)) {
			$this->session->set_userdata('logined', true);
				$this->session->set_userdata('username_admin',$cek_login_admin->username_admin);
				$this->session->set_userdata('status','admin');
				redirect("home");
				//print_r("berhasil login admin");

			}
			else 
			{
$this->session->set_flashdata('gagal','<div class="alert alert-danger"> <Strong>Gagal Login</strong> username dan password anda salah. </div>');

				redirect("login2");

							}
		}
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		$this->session->unset_userdata('username_member');
		$this->session->unset_userdata('username_admin');

		$this->session->unset_userdata('status');
		//$this->session->unset_userdata('cart');
		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */